# Generated by Django 4.1.1 on 2022-09-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='is_returned',
        ),
    ]
