# Generated by Django 4.1.1 on 2022-09-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('FACULTY', 'FACULTY'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=20),
        ),
    ]
